[package]
name = "av1-obu-parser"
version = "0.1.0-alpha.1"
edition = "2024"
description = "A pure Rust parser for AV1 OBU bitstreams and IVF containers."
license = "MIT"
readme = "README.md"
repository = "https://github.com/mycrl/av1-obu-parser"
homepage = "https://github.com/mycrl/av1-obu-parser"
exclude = ["assets/sample.ivf"]

[[example]]
name = "simple"

[dependencies]

[dev-dependencies]
tokio = { version = "1.34.0", features = ["full"] }
clap = { version = "4.5.19", features = ["derive"] }
